version: '3.8'

services:
  mssql-server-db:
    container_name: mssql-server-db
    image: mcr.microsoft.com/mssql/server
    user: root
    ports:
      - "1433:1433"
    networks:
      - bankingsystemnetwork
    environment:
      SA_PASSWORD: Password123
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlserver:/var/opt/mssql/data

  banking-system:
    image: bankingsystem:latest
    container_name: bankingsystem
    ports:
      - 5000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    networks:
      - bankingsystemnetwork
    depends_on:
      - mssql-server-db

volumes:
  mssqlserver:
    driver: local

networks:
  bankingsystemnetwork:
    name: banking-network